ci(gh-actions): update audit

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -47,11 +47,15 @@ jobs:
         uses: actions/checkout@v3
       - name: Set up Homebrew
         uses: Homebrew/actions/setup-homebrew@master
-      - name: Set tap
-        run: brew tap PunGrumpy/formulas
-      - name: brew audit formula
+      - name: Audit Homebrew Formulas
         run: |
+          set -e
           for file in Formula/*.rb; do
-            formula=$(echo $file | sed 's/\.rb//g')
-            brew audit --formula PunGrumpy/formulas/$formula
+            formula=$(basename "$file" .rb)
+            echo "Auditing $formula"
+            if brew audit pungrumpy/formulas/$formula; then
+              echo "$formula audit passed"
+            else
+              echo "Error: $formula audit failed"
+            fi
           done
